Done task
DmytroPiskun/test-task2-nextjs pull request #1
Opened 2021-07-08 08:48 UTC by DmytroPiskun

2021-07-08 10:55 UTC, dmytro-devima-solutions requested changes

2021-07-08 10:55 UTC, dmytro-devima-solutions commented on components/404Page/index.tsx
> +import React from "react";
Реакт можна не імпортувати

2021-07-08 10:55 UTC, dmytro-devima-solutions commented on components/AuthPage/index.tsx
> +      "https://www.linkedin.com/oauth/v2/authorization?response_type=code&client_id=77h78eh2ef1age&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Fcallback&scope=r_liteprofile%20r_emailaddress";
client_id має бути у .env
redirect_uri буде не валідним дляко запустити апку на іншому компі, зроби щоб у redirect_uri підставлявся поточний хостнейм

2021-07-08 10:55 UTC, dmytro-devima-solutions commented on components/AuthPage/index.tsx
> +      <Button
Це може бути просто лінка, тоді тобі не потрібні махінації з onClick

2021-07-08 10:55 UTC, dmytro-devima-solutions commented on components/LoadingPage/index.tsx
> +import React from "react";
Імпорт не потрібен і далі теж

2021-07-08 10:55 UTC, dmytro-devima-solutions commented on components/UserCard/index.tsx
> +        {typeof data === "undefined" ? (
достатньо перевірки `data ? ... : ...`

2021-07-08 10:55 UTC, dmytro-devima-solutions commented on package-lock.json
> +{
Удоли

2021-07-08 10:55 UTC, dmytro-devima-solutions commented on package.json
> +    "babel-plugin-styled-components": "^1.13.1",
Де ти це юзаєш?

2021-07-08 10:55 UTC, dmytro-devima-solutions commented on pages/_app.tsx
> +MyApp.propTypes = {
propTypes не потрібні у typescript

2021-07-08 10:55 UTC, dmytro-devima-solutions commented on pages/callback.tsx
> +  useEffect(() => {
Навіщо ти тут щось робиш, якщо цей компонент ніколи не рендериться?

2021-07-08 10:55 UTC, dmytro-devima-solutions commented on pages/callback.tsx
> +    const authorizedResponseAdress = "https://api.linkedin.com/v2/me";
Повидвляй по всьому проекту змінні і імпоти які не юзаються

2021-07-08 10:55 UTC, dmytro-devima-solutions commented on pages/callback.tsx
> +    const resp = await axios
Усі виклики axios виносять у окремі функції, які кладуть у services

2021-07-08 10:55 UTC, dmytro-devima-solutions commented on pages/callback.tsx
> +    cookies.set("accessToken", accessToken); // set token in cookies
Сетання токена у кукі варто винести у окрему функцію

2021-07-08 10:55 UTC, dmytro-devima-solutions commented on pages/callback.tsx
> +      .then((res: AxiosResponse) => res.data);
Додай тип респонсу у AxiosResponse

2021-07-08 10:55 UTC, dmytro-devima-solutions commented on pages/userProfile.tsx
> +    const accessToken = cookies.get("accessToken");
Винеси отримання токена з кукі у окрему функцію

2021-07-09 09:17 UTC, dmytro-devima-solutions requested changes

2021-07-09 09:17 UTC, dmytro-devima-solutions commented on components/AuthPage/index.tsx
>  import { Button } from "@material-ui/core";
- `import React from "react";`

2021-07-09 09:17 UTC, dmytro-devima-solutions commented on components/AuthPage/index.tsx
> +  const redirect_uri = "http%3A%2F%2Flocalhost%3A3000%2F";
Навіщо тобі ця змінна?

2021-07-09 09:17 UTC, dmytro-devima-solutions commented on example.env
> +NEXT_PUBLIC_REDIRECT_URL = your hostname in query style. For example http%3A%2F%2Flocalhost%3A3000%2F
Зроби нормальний формат. А у коді перетвори через URLSearchParams

2021-07-09 09:17 UTC, dmytro-devima-solutions commented on pages/_app.tsx
>  import React from "react";
- `import React from "react";`

2021-07-09 09:17 UTC, dmytro-devima-solutions commented on pages/_app.tsx
>      </React.Fragment>
Якщо ти не передаєш у `<React.Fragment>...</React.Fragment>` key, то можна замінити його на коротку форму `<>...</>`

2021-07-09 09:17 UTC, dmytro-devima-solutions commented on pages/callback.tsx
>            redirect_uri: "http://localhost:3000/callback",
не думаю, що тут потрібен параметр redirect_uri

2021-07-09 09:17 UTC, dmytro-devima-solutions commented on services/generateBaseDataResponse.ts
> +  const initialState = {
Лиши тут тільки поля, які використовуєш

2021-07-09 09:17 UTC, dmytro-devima-solutions commented on services/getAllResponseData.ts
> +export async function getAllResponseData(accessToken: string) {
Нормальну назву дай функції, щоб було зрозуміло що вона робить

2021-07-09 09:17 UTC, dmytro-devima-solutions commented on services/tokenAndCookies.ts
> +  tokenName: string,
tokenName у тебе вже є "accessToken", навіщо його передавати?

2021-07-09 09:17 UTC, dmytro-devima-solutions commented on services/types.ts
> +export interface IRootState {
Що стейт редюсера робить у сервісах?

2021-07-14 14:10 UTC, DevimaSolutions commented on pages/callback.tsx
> +    const resp = await getLinkedInToken(codeForGettingToken);
Якщо функція називається getLinkedInToken, вона мала б повертати токен, а не об'єкт з токеном всередині

2021-07-14 14:10 UTC, DevimaSolutions commented on pages/userProfile.tsx
> +      const userDataResponse = await getLinkedInUserData(accessToken);
userDataResponse -> userData

2021-07-14 14:10 UTC, DevimaSolutions commented on pages/userProfile.tsx
>        userDataResponse.profilePictureDirectLink = imgAdress;
Це мало б робитись всередині сервісу

2021-07-14 14:10 UTC, DevimaSolutions commented on services/getLinkedInToken.ts
> +    return "error_access_token";
Так не роблять. Забери try catch і перевіряй вже при виклику сервісу чи не викинуло ексепшн

2021-07-14 14:10 UTC, DevimaSolutions commented on utils/cookies.ts
>    return token;
`return getDataFromCookies("accessToken", req, res);`

2021-07-14 14:14 UTC, DevimaSolutions commented on components/404Page/images/Group404.svg
> +<svg width="280" height="113" viewBox="0 0 280 113" fill="none" xmlns="http://www.w3.org/2000/svg">
Усі картинки мають лежати у `public/assets`

2021-07-14 14:14 UTC, DevimaSolutions commented on components/404Page/index.tsx
> +        )}
Замість 
```
{isNav ? (
  <div className={classes.menuWrapper}>
    <Image onClick={handleClick} src={menuCross} alt="menu" />
  </div>
) : (
  <div className={classes.menuWrapper}>
    <Image onClick={handleClick} src={menuButton} alt="menu" />
  </div>
)}
```
можна написати
```
<div className={classes.menuWrapper}>
  <Image onClick={handleClick} src={isNav ? menuCross : menuButton} alt="menu" />
</div>
```

2021-07-14 14:19 UTC, DevimaSolutions commented on components/404Page/index.tsx
> -            src={proxyDropEmblem}
Доступ до усіх картинок з public має бути через url, а не через імпорт
eg. `src='/Group6.svg'`

2021-07-14 14:19 UTC, DevimaSolutions commented on components/404Page/Content/styles.ts
> +    maxWidth: "500px",
Використовуй цифри замість рядків з пікселями коли можливо `maxWidth: 500`

2021-07-15 09:17 UTC, DevimaSolutions commented on components/404Page/Content/index.tsx
> +          width="500px"
Використовуй цифри замість тексту з пікселями де можливо

2021-07-15 09:17 UTC, DevimaSolutions commented on components/404Page/Content/index.tsx
> +          src={"/assets/Group404.svg"}
Тут не потібні фігурні скобки `src="/assets/Group404.svg"`. І далі перевір

2021-07-15 09:17 UTC, DevimaSolutions commented on components/404Page/index.tsx
>    const [isNav, setIsNav] = useState(false);
Не жалій букв на назви змінних isMobileNavOpen

2021-07-15 09:17 UTC, DevimaSolutions commented on services/getLinkedInUserData.ts
> +  responseData.data.profilePictureDirectLink = imgAdress;
Модифікувати об'єкти цце не дуже добре, старайся робити це через створення нового об'єкту з деструктуризацією полів у нього
`return {...response.data, profilePictureDirectLink}`

2021-07-15 10:31 UTC, DevimaSolutions commented on components/404Page/Nav/styles.ts
> +  root: {},
Навіщо тобі цей клас?

2021-07-15 10:31 UTC, DevimaSolutions commented on components/404Page/styles.ts
> +      backgroundImage: "  url(assets/backlines.svg)",
пробіли

2021-07-15 10:31 UTC, DevimaSolutions commented on components/UserCard/index.tsx
> +          <>
<> тут не потрібен

2021-07-15 10:31 UTC, DevimaSolutions commented on package.json
> +    "material-ui": "^0.20.2",
Цей пакет тобі по ідеї не треба

2021-07-15 10:31 UTC, DevimaSolutions commented on pages/404.tsx
> +export default function ErorrPage() {
Нормальні назви компоненту і імпорту

2021-07-15 10:31 UTC, DevimaSolutions commented on pages/_app.tsx
> +import React from "react";
Забирай

2021-07-15 10:31 UTC, DevimaSolutions commented on tsconfig.json
> +  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", "pages/_document.tsx", "pages/_app.js"],
Ці пейджі вже мали б бути включені правилом `"**/*.tsx"`

2021-07-15 11:54 UTC, DevimaSolutions commented on pages/404.tsx
> +export default function ErorrPage() {
Слова `Erorr` не існує

2021-07-15 11:54 UTC, DevimaSolutions commented on components/UserCard/index.tsx
> +            ></img>
`></img>` => `/>`

2021-07-15 12:42 UTC, DevimaSolutions commented on components/UserCard/index.tsx
> +          ></Image>
У інших місцях теж можна було здогадатись поправити теги

2021-07-15 12:42 UTC, DevimaSolutions commented on components/ErrorPageComponent/index.tsx
> +    setIsMobelieNavOpen(!isMobileNavOpen);
Коли оновлення стейту базується на попередньому стейті, зміну описують функцією
setIsMobelieNavOpen(value => !value);

2021-07-15 13:10 UTC, merged